filebeat.inputs: 
     - type: log
       enabled: true
       paths: /usr/share/filebeat/logs/suricata.log
       fields:
         event.type: suricata

output.logstash:
   hosts: ["192.168.57.5:5044"]

   