---

# - name: copy synlite_suricata folder
#   copy:
#    src: /home/islem/Documents/Project/PFEGITHUB2/ansible/synlite_suricata
#    dest: "{{ elk_conf_dir }}"
# - name: copy pipelines folder
#   copy:
#    src: /home/islem/Documents/Project/PFEGITHUB2/ansible/pipelines
#    dest: "{{ elk_conf_dir }}"
#   notify: Restart logstash container  
- name: copy pipeline yml file
  copy:
   src: files/pipelines.yml
   dest: "{{ elk_conf_dir }}/pipelines.yml"
  notify: Restart logstash container      

...